apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuance-frontend
  namespace: kube-credential
  labels:
    app: issuance-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issuance-frontend
  template:
    metadata:
      labels:
        app: issuance-frontend
    spec:
      containers:
      - name: issuance-frontend
        image: akshaykumar33/kube-credential-issuance-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        #for local m/c
        # - name: VITE_API_URL
        #   value: "http://verification-service:3000"
        #for browser  
          # - name: VITE_API_URL
          #   value: "http://issuance-service.kube-credential.svc.cluster.local:3000"
        #for pods acessing each other outside
          - name: VITE_API_URL
            value: "http://3.110.212.85:3000"
        resources:
          limits:
            memory: "125Mi"
            cpu: "100m"
          requests:
            memory: "125Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: issuance-frontend
  namespace: kube-credential
spec:
  selector:
    app: issuance-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---