apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-frontend
  namespace: kube-credential
  labels:
    app: verification-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verification-frontend
  template:
    metadata:
      labels:
        app: verification-frontend
    spec:
      containers:
      - name: verification-frontend
        image: akshaykumar33/kube-credential-verification-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://verification-service.kube-credential.svc.cluster.local:3001"
        resources:
          limits:
            memory: "125Mi"
            cpu: "100m"
          requests:
            memory: "125Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: verification-frontend
  namespace: kube-credential
spec:
  selector:
    app: verification-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---