name: CI-CD Pipeline

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Issuance Image
      uses: docker/build-push-action@v4
      with:
        context: ./services/issuance-service
        push: true
        tags: docker.io/akshaykumar33/kube-credential-issuance:latest

    - name: Build & Push Verification Image
      uses: docker/build-push-action@v4
      with:
        context: ./services/verification-service
        push: true
        tags: docker.io/akshaykumar33/kube-credential-verification:latest

    - name: Build & Push Issuance Frontend Image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend/issuance-app
        push: true
        tags: docker.io/akshaykumar33/kube-credential-issuance-ui:latest

    - name: Build & Push Verification Frontend Image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend/verification-app
        push: true
        tags: docker.io/akshaykumar33/kube-credential-verification-ui:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest

    - name: Configure kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Kubernetes Deployments Rollout Restart
      run: |
        kubectl rollout restart deployment/issuance-service -n kube-credential
        kubectl rollout restart deployment/verification-service -n kube-credential
        kubectl rollout restart deployment/issuance-frontend -n kube-credential
        kubectl rollout restart deployment/verification-frontend -n kube-credential
