name: Kube Credential CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: kube-secrete
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ======================
    # BACKEND IMAGES
    # ======================
    - name: Build & push Issuance Backend
      uses: docker/build-push-action@v6
      with:
        context: ./services/issuance-service
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/kube-credential-issuance:latest

    - name: Build & push Verification Backend
      uses: docker/build-push-action@v6
      with:
        context: ./services/verification-service
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/kube-credential-verification:latest

    # ======================
    # FRONTEND IMAGES
    # ======================
    - name: Build & push Issuance Frontend
      uses: docker/build-push-action@v6
      with:
        context: ./frontend/issuance-app
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/kube-credential-issuance-ui:latest

    - name: Build & push Verification Frontend
      uses: docker/build-push-action@v6
      with:
        context: ./frontend/verification-app
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/kube-credential-verification-ui:latest

    # ======================
    # COPY ONLY k8s FOLDER TO EC2
    # ======================
    - name: Copy Kubernetes manifests to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./kube-credential-k8s/"
        target: "~/kube-credential/"

    # ======================
    # DEPLOY ON EC2
    # ======================
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/kube-credential/
          chmod +x deploy.sh
          echo "ðŸš€ Starting deployment in background..."
          nohup ./deploy.sh > deploy.log 2>&1 &
