name: CI-CD Pipeline for EC2 Kubernetes

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAMESPACE: akshaykumar33
  KUBE_NAMESPACE: kube-credential

jobs:
  build-and-deploy:
    runs-on: self-hosted

    # Uncomment and replace if using environment secrets
    environment: kube-secrete

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List repo files for debugging
      run: ls -lR

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Issuance Image
      uses: docker/build-push-action@v4
      with:
        context: ./services/issuance-service
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/issuance-service:latest

    - name: Build & Push Verification Image
      uses: docker/build-push-action@v4
      with:
        context: ./services/verification-service
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/verification-service:latest

    - name: Build & Push Issuance Frontend Image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend/issuance-app
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/issuance-frontend:latest

    - name: Build & Push Verification Frontend Image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend/verification-app
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/verification-frontend:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest

    - name: Create kube directory
      run: mkdir -p $HOME/.kube

    - name: Configure kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Deploy Manifests and Rollout Restart
      run: |
        kubectl apply -f kube-credential-k8s/k8s/namespace.yaml
        kubectl apply -f kube-credential-k8s/k8s/
        kubectl rollout restart deployment/issuance-service -n kube-credential
        kubectl rollout restart deployment/verification-service -n kube-credential
        kubectl rollout restart deployment/issuance-frontend -n kube-credential
        kubectl rollout restart deployment/verification-frontend -n kube-credential
